--- #YAML:1.0
name:               Set-Formula
version:            0.01
abstract:           ~
author:
    - Mart Rivilis <mrivilis@gmail.com>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Carp:        0
    Test::More:  0
requires:
    perl:  5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
